### PR TITLE
cipher: improve `encrypt_padded_vec` methods

### LINKED ISSUE #2100: encrypt_padded_vec::<NoPadding>() panics when called with unpadded buffer
Following code panics with

```rust
use aes::Aes128Enc;
use cipher::{BlockCipherEncrypt, KeyInit, block_padding::NoPadding};

fn main() {
    let key = [1; 16];
    let msg = [2; 15];

    let encryptor = Aes128Enc::new(&key.into());
    encryptor.encrypt_padded_vec::<NoPadding>(&msg);
}
```
```toml
[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = { version = "=0.9.0-rc.2", default-features=false }
cipher = { version = "=0.5.0-rc.2", default-features=false, features = ["alloc", "block-padding"] }
```

console output:
```
RUST_BACKTRACE=1 cargo run   
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/hello`

thread 'main' (9097) panicked at /home/dobo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.5.0-rc.2/src/block.rs:139:14:
enough space for encrypting is allocated: PadError
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect
             at /usr/src/debug/rust/rustc-1.91.1-src/library/core/src/result.rs:1178:23
   4: cipher::block::BlockCipherEncrypt::encrypt_padded_vec
             at /home/dobo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.5.0-rc.2/src/block.rs:139:14
   5: hello::main
             at ./src/main.rs:9:15
   6: core::ops::function::FnOnce::call_once
             at /usr/src/debug/rust/rustc-1.91.1-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`NoPadding::pad_detached()` returns `PaddedData::Error` which gets propagated into `encrypt_padded_vec()`. Then it's unwrapped using `expect()` and panics. Backtrace when breakpoint set to `pad_detached()`:
```
* frame #0: 0x0000555555576342 hello`<block_padding::NoPadding as block_padding::Padding>::pad_detached(data=size=15) at lib.rs:372:13
  frame #1: 0x00005555555719c6 hello`cipher::block::BlockCipherEncrypt::encrypt_padded_inout [inlined] inout::reserved::InOutBufReserved<u8>::into_padded_blocks(self=<unavailable>) at reserved.rs:165:42
  frame #2: 0x0000555555571977 hello`cipher::block::BlockCipherEncrypt::encrypt_padded_inout(self=0x00007fffffffccb0, data=<unavailable>) at block.rs:94:28
  frame #3: 0x0000555555571735 hello`cipher::block::BlockCipherEncrypt::encrypt_padded_b2b(self=0x00007fffffffccb0, msg=size=15, out_buf=size=16) at block.rs:127:14
  frame #4: 0x0000555555571862 hello`cipher::block::BlockCipherEncrypt::encrypt_padded_vec(self=0x00007fffffffccb0, msg=size=15) at block.rs:138:14
  frame #5: 0x00005555555757c7 hello`hello::main at main.rs:9:15
```

I've got two questions regarding that:
1) Is this an intended behavior? If so, I think it should be explicitly mentioned in the documentation of  `encrypt_padded_vec()` that it will panic when `encrypt_padded_vec::<NoPadding>()` is called with unpadded buffer argument.
2) If not, maybe it's worth making `encrypt_padded_vec()` fallible (I'm aware that it's an API breaking change):

```diff
diff --git a/cipher/src/block.rs b/cipher/src/block.rs
index b930199..5486004 100644
--- a/cipher/src/block.rs
+++ b/cipher/src/block.rs
@@ -130,16 +130,13 @@ pub trait BlockCipherEncrypt: BlockSizeUser + Sized {
     /// Pad input and encrypt into a newly allocated Vec. Returns resulting ciphertext Vec.
     #[cfg(all(feature = "block-padding", feature = "alloc"))]
     #[inline]
-    fn encrypt_padded_vec<P: Padding>(&self, msg: &[u8]) -> Vec<u8> {
+    fn encrypt_padded_vec<P: Padding>(&self, msg: &[u8]) -> Result<Vec<u8>, PadError> {
         use crypto_common::typenum::Unsigned;
         let bs = Self::BlockSize::USIZE;
         let mut out = vec![0; bs * (msg.len() / bs + 1)];
-        let len = self
-            .encrypt_padded_b2b::<P>(msg, &mut out)
-            .expect("enough space for encrypting is allocated")
-            .len();
+        let len = self.encrypt_padded_b2b::<P>(msg, &mut out)?.len();
         out.truncate(len);
-        out
+        Ok(out)
     }
 }
 
@@ -374,16 +371,13 @@ pub trait BlockModeEncrypt: BlockSizeUser + Sized {
     /// Pad input and encrypt into a newly allocated Vec. Returns resulting ciphertext Vec.
     #[cfg(all(feature = "block-padding", feature = "alloc"))]
     #[inline]
-    fn encrypt_padded_vec<P: Padding>(self, msg: &[u8]) -> Vec<u8> {
+    fn encrypt_padded_vec<P: Padding>(self, msg: &[u8]) -> Result<Vec<u8>, PadError> {
         use crypto_common::typenum::Unsigned;
         let bs = Self::BlockSize::USIZE;
         let mut out = vec![0; bs * (msg.len() / bs + 1)];
-        let len = self
-            .encrypt_padded_b2b::<P>(msg, &mut out)
-            .expect("enough space for encrypting is allocated")
-            .len();
+        let len = self.encrypt_padded_b2b::<P>(msg, &mut out)?.len();
         out.truncate(len);
-        out
+        Ok(out)
     }
 }
```

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #2100

### CODE REVIEW

File: cipher/src/block.rs [hunk 1]
```diff
@@ -127,19 +127,37 @@ pub trait BlockCipherEncrypt: BlockSizeUser + Sized {
...
-    /// Pad input and encrypt into a newly allocated Vec. Returns resulting ciphertext Vec.
+    /// Pad `msg` with padding algorithm `P`, encrypt it into a newly allocated `Vec`,
+    /// and return the resulting ciphertext vector.
+    ///
+    /// # Panics
+    /// If `NoPadding` is used with a message size that is not a multiple of the cipher block size.
     #[cfg(all(feature = "block-padding", feature = "alloc"))]
     #[inline]
-    fn encrypt_padded_vec<P: Padding>(&self, msg: &[u8]) -> Vec<u8> {
+    fn encrypt_padded_vec<P: Padding + 'static>(&self, msg: &[u8]) -> Vec<u8> {
```
Comment (newpavlov) [inline cipher/src/block.rs]: I probably will release `block-padding` v0.4.2 with added `'static` bound on `Padding` and will yank v0.4.1.

File: Cargo.toml [hunk 2]
```diff
@@ -17,4 +17,5 @@ members = [
 digest = { path = "digest" }
 signature = { path = "signature" }
 
+block-padding = { git = "https://github.com/RustCrypto/utils", branch = "block-padding/static_bound" }
```
Comment (newpavlov) [inline Cargo.toml]: TODO: remove after `block-padding` v0.4.2 is released
